project:
  type: website
  render:
    - "*.qmd"
    - "!fable5_improve/"

website:
  title: "Kezhou Xiao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: book-project.qmd
        text: Book Project
  page-footer:
    left: "© 2026 Kezhou Xiao"
    right: "Last updated July 2026"

format:
  html:
    theme:
      - default
      - ink-celadon.scss
    toc: true
    include-in-header: analytics.html

editor: visual

